service: lulubell

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: ap-northeast-1
  environment:
    APP_ENV: production
    QUEUE_CONNECTION: sqs-fifo
    SQS_QUEUE: ${construct:jobs.queueUrl}
  ecr:
    images:
      lulubell:
        path: ./
      lulubell-artisan:
        path: ./
        file: Dockerfile.artisan
      lulubell-queue:
        path: ./
        file: Dockerfile.queue
  vpc:
    securityGroupIds:
      Fn::Split: [',', '${env:LAMBDA_VPC_SECURITY_GROUP_IDS}']
    subnetIds:
      Fn::Split: [',', '${env:LAMBDA_VPC_SUBNET_IDS}']

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

functions:
  web:
    image:
      name: lulubell
    timeout: 28
    events:
      - httpApi: '*'
  artisan:
    image:
      name: lulubell-artisan
    timeout: 720

constructs:
  jobs:
    type: queue
    fifo: true
    worker:
      image:
        name: lulubell-queue
      timeout: 900
      reservedConcurrency: 1

plugins:
  - ./vendor/bref/bref
  - serverless-lift
  - serverless-domain-manager
  - serverless-api-gateway-throttling

custom:
  customDomain:
    domainName: lulubell.miraiportal.com
    endpointType: REGIONAL
    apiType: http
    autoDomain: true
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1
